origen/origen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('sensor/', include('sensor.urls', namespace='sensor'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

origen/sensor/urls.py
from django.urls import path, include 
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'sensor'
  
urlpatterns = [
    path('for/<slug>/', views.SensorList.as_view(), name='all'),
    path('for/<slug>/create/', views.CreateSensor.as_view(), name='create'),
    path('for/<slug>/<pk>', views.SensorDetail.as_view(), name='single'),
    path('for/<slug>/<pk>/update/', views.UpdateSensor.as_view(), name='update'),
    path('for/<slug>/<pk>/delete/', views.DeleteSensor.as_view(), name='delete'),
    path('api/for/<slug>/<pk>', views.SensorDetailAPI.as_view(), name='single-api'),
    path('api/for/<slug>/<pk>/records/<time>/<offset>', views.RecordTimeAPI.as_view(), name='time-records'),
    path('api/for/<slug>/', views.SensorListAPI.as_view(), name='sensor-list'),
    path('api/for/<slug>/<pk>/new/record/', views.NewRecordAPI.as_view(), name='new-record'),
]

origen/templates/baseLogin.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>OrigenAir</title>

    <!-- Front Awesome Used in Top Bar-->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.12.0/css/all.css"
        integrity="sha384-ekOryaXPbeCpWQNxMwSWVvQ0+1VrStoPJq54shlYhR8HzQgig1v5fas6YgOqLoKz" crossorigin="anonymous">

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
        </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
        </script>

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- Stylesheet CSS -->
    <link href="{% static 'css/accounts.css' %}" rel="stylesheet" type="text/css" media="all" />
</head>

<div class="container">
    <div class="row">
        <div class="col-lg-10 col-xl-9 mx-auto">
            <div class="card card-signin flex-row my-5">
                <!-- IMAGE -->
                <div class="card-img-left d-none d-md-flex">
                    <!-- Background image for card set in CSS! -->
                </div>
                <!-- /END IMAGE -->
                
                <!-- CONTENT -->
                <div class="card-body">
                    <!-- CLOSE BUTTON -->
                    <div class="text-right">
                        <a class="large" href="{% url 'login' %}" style="color:rgb(27, 154, 75)"><i class="fas fa-times"></i></a>
                    </div>
                    <!-- /END CLOSE BUTTON -->

                    <!--LOGO IMAGE-->
                    <div class="text-center">
                        <img id="logo" src="{% static 'img/logo2.png' %}" width="60">
                    </div>
                    <!-- /END LOGO IMAGE -->

                    <!-- CONTENT -->

                    <body>
                        {% block content %}
                        {% endblock %}
                    </body>
                    <!-- /END CONTENT -->
                </div>
            </div>
        </div>
    </div>
</div>

</html>

origen/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block content %}

{% if user.person.organization %}
<input type="hidden" id="orgSlug" name="hiddenOrgName" value="{{ user.person.organization.slug }}">
<div class="main-container">
    <div class="row">
        <!-- ACTIVE SENSORS -->
        <div class="col-sm-4 index-card-margin3">
            <div class="card border-0 shadow">
                <div class="card-body2 text-center index-card1 index-card-padding">
                    <div class="card3">
                        <div>
                            <h5 class="card-title mb-0 index-card1-text">Active Sensors</h5>
                        </div>
                        <div class="card-text2 index-card1-text index-card1-text-margin">
                            <h5 id="activeCount">0</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /END ACTIVE SENSORS -->

        <!-- INACTIVE SENSORS -->
        <div class="col-sm-4 index-card-margin3">
            <div class="card border-0 shadow">
                <div class="card-body2 text-center index-card1 index-card-padding">
                    <div class="card3">
                        <div>
                            <h5 class="card-title mb-0 index-card1-text">Inactive Sensors</h5>
                        </div>
                        <div class="card-text2 index-card1-text index-card1-text-margin">
                            <h5 id="inactiveCount">0</h5>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <!-- /END INACTIVE SENSORS -->

        <!-- TOTAL SENSORS -->
        <div class="col-sm-4 index-card-margin3">
            <div class="card border-0 shadow">
                <div class="card-body2 text-center index-card1 index-card-padding">
                    <div class="card3">
                        <div>
                            <h5 class="card-title mb-0 index-card1-text">Total Sensors</h5>
                        </div>
                        <div class="card-text2 index-card1-text index-card1-text-margin">
                            <h5 id="totalCount">0</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /END TOTAL SENSORS -->

        <!-- Temperature Gauge -->
        <div class="col-sm-3 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <div id="chartdiv1" style="width: 100%; height: 41.28vh; margin-left: -2%"></div>
            </div>
        </div>

        <!-- Temperature Line -->
        <div class="col-sm-9 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <canvas id="line-chart1" height="400vh"></canvas>
            </div>
        </div>

        <!-- Humidity Gauge -->
        <div class="col-sm-3 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <div id="chartdiv2" style="width: 100%; height: 41.28vh; margin-left: -2%"></div>
            </div>
        </div>

        <!-- Humidity Line -->
        <div class="col-sm-9 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <canvas id="line-chart2" height="400vh"></canvas>
            </div>
        </div>

        <!-- VOC Gauge -->
        <div class="col-sm-3 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <div id="chartdiv3" style="width: 100%; height: 41.28vh; margin-left: -2%"></div>
            </div>
        </div>

        <!-- VOC Line -->
        <div class="col-sm-9 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <canvas id="line-chart3" height="400vh"></canvas>
            </div>
        </div>

        <!-- CO2 Gauge -->
        <div class="col-sm-3 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <div id="chartdiv4" style="width: 100%; height: 41.28vh; margin-left: -2%"></div>
            </div>
        </div>

        <!-- CO2 Line -->
        <div class="col-sm-9 index-card-margin3">
            <div class="card border-0 shadow index-card-padding">
                <canvas id="line-chart4" height="400vh"></canvas>
            </div>
        </div>
    </div>
</div>

{% else %}

<body style="background-color: lightcyan;">
    <div class="index-container">
        <div class="row justify-content-center index-card-margin">
            <!-- Create Organization-->
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11 mt-4 index-card-margin2">
                <div class="card text-center h-100">
                    <div class="card-body px-5 pt-5 d-flex flex-column">
                        <div>
                            <div class="h3 text-primary font-weight-400">Create</div>
                            <p class="text-muted mb-4">Create an organization and invite new members</p>
                        </div>
                        <div class="icons-org-create align-items-center mx-auto mt-auto">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-users icon-users">
                                <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                <circle cx="9" cy="7" r="4"></circle>
                                <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                                <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                <circle cx="9" cy="7" r="4"></circle>
                                <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                            </svg>
                            <svg class="svg-inline--fa fa-plus fa-w-14 icon-plus" aria-hidden="true" focusable="false"
                                data-prefix="fas" data-icon="plus" role="img" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 448 512" data-fa-i2svg="">
                                <path fill="currentColor"
                                    d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z">
                                </path>
                                <path fill="currentColor"
                                    d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z">
                                </path>
                            </svg>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent px-5 py-4">
                        <div class="small text-center"><a class="btn btn-block btn-primary"
                                href="{% url 'organization:create' %}">Create new organization</a></div>
                    </div>
                </div>
            </div>

            <!-- Join Organization-->
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11 mt-4 index-card-margin2">
                <div class="card text-center h-100">
                    <div class="card-body px-5 pt-5 d-flex flex-column">
                        <div>
                            <div class="h3 text-secondary font-weight-400">Join</div>
                            <p class="text-muted mb-4">View and join an organization</p>
                        </div>
                        <div class="icons-org-join align-items-center mx-auto mt-auto">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-user icon-user">
                                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                <circle cx="12" cy="7" r="4"></circle>
                            </svg>
                            <svg class="svg-inline--fa fa-long-arrow-alt-right fa-w-14 icon-arrow" aria-hidden="true"
                                focusable="false" data-prefix="fas" data-icon="long-arrow-alt-right" role="img"
                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
                                <path fill="currentColor"
                                    d="M313.941 216H12c-6.627 0-12 5.373-12 12v56c0 6.627 5.373 12 12 12h301.941v46.059c0 21.382 25.851 32.09 40.971 16.971l86.059-86.059c9.373-9.373 9.373-24.569 0-33.941l-86.059-86.059c-15.119-15.119-40.971-4.411-40.971 16.971V216z">
                                </path>
                            </svg>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-users icon-users">
                                <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                <circle cx="9" cy="7" r="4"></circle>
                                <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent px-5 py-4">
                        <div class="small text-center"><a class="btn btn-block btn-secondary"
                                href="{% url 'organization:all' %}">Join an organization</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endif %}

{% endblock %}

{% block scripts %}
{{block.super}}
<!-- chart.js -->
<script src="{% static 'js/charts.js' %}"></script>
<!-- amCharts.js -->
<script src="{% static 'js/amCharts.js' %}"></script>
<!-- cards.js -->
<script src="{% static 'js/cards.js' %}"></script>
{% endblock scripts %}