origen/origen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('sensor/', include('sensor.urls', namespace='sensor'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

origen/sensor/urls.py
from django.urls import path, include 
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'sensor'
  
urlpatterns = [
    path('for/<slug>/', views.SensorList.as_view(), name='all'),
    path('for/<slug>/create/', views.CreateSensor.as_view(), name='create'),
    path('for/<slug>/<pk>', views.SensorDetail.as_view(), name='single'),
    path('for/<slug>/<pk>/update/', views.UpdateSensor.as_view(), name='update'),
    path('for/<slug>/<pk>/delete/', views.DeleteSensor.as_view(), name='delete'),
    path('api/for/<slug>/<pk>', views.SensorDetailAPI.as_view(), name='single-api'),
    path('api/for/<slug>/<pk>/records/<time>/<offset>', views.RecordTimeAPI.as_view(), name='time-records'),
    path('api/for/<slug>/', views.SensorListAPI.as_view(), name='sensor-list'),
    path('api/for/<slug>/<pk>/new/record/', views.NewRecordAPI.as_view(), name='new-record'),
]

origen/sensors/urls.py
from django.urls import path, include 
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'sensors'

urlpatterns = [
    path('create/', views.CreateSensor.as_view(), name='create'),
    path('detail/', views.SensorDetail.as_view(), name='single'),
    path('update/', views.UpdateSensor.as_view(), name='update')
    # path('', views..as_view(), name='all'),
]

origen/sensor/models.py
from django.db import models
from django.utils import timezone
from organization.models import Organization
from accounts.models import Person
from django.utils.text import slugify
from django.urls import reverse
from django.utils.translation import gettext as _

# Create your models here.

class Sensor(models.Model):
    TEMPERATURE = 'temperature'
    HUMIDITY = 'humidity'
    VOC = 'voc'
    CO2 = 'co2'
    #Types of sensors 
    TYPES = [
        (TEMPERATURE, _('Temperature')),
        (HUMIDITY, _('Humidity')),
        (VOC, _('Volatile Organic Compound')),
        (CO2, _('Carbon Dioxide')),
    ]
    
    name = models.CharField(max_length=25, null=False, blank=False)
    organization = models.ForeignKey(Organization, related_name='sensors', null=True, blank=True, on_delete=models.CASCADE)
    sensor_type = models.CharField(max_length=100, choices=TYPES, default='None')
    value = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    threshold_min = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    threshold_max = models.DecimalField(max_digits=10, decimal_places=2, default=100)
    last_updated = models.DateTimeField(default=timezone.now, null=True, blank=True)
    
    def __str__(self):
        return self.name

    def save(self,  *args, **kwargs):
        self.last_updated = timezone.now()
        super(Sensor, self).save(*args,**kwargs)
        Record.objects.create(
            sensor = self,
            value = self.value,
        )

class Record(models.Model):
    sensor = models.ForeignKey(Sensor, related_name='records', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now, null=False)
    value = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.sensor.name + " @ " + str(self.created_at)

origen/sensor/forms.py
from django import forms
from sensor.models import Sensor
from django.forms import ModelForm

class SensorCreateForm(forms.ModelForm):
    
    class Meta:
        model = Sensor
        fields = ('name', 'sensor_type', 'threshold_min', 'threshold_max')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputSensorName',
                                        'placeholder': 'Name',
                                        'name': 'sensor-name'}),
            'sensor_type': forms.Select(attrs={'class': 'form-control',
                                        'id': 'inputType',
                                        'placeholder': 'Type',
                                        'name': 'sensor-type'}),
            'threshold_min': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputThresholdMin',
                                        'placeholder': 'Min',
                                        'name': 'threshold-min'}),
            'threshold_max': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputThresholdMax',
                                        'placeholder': 'Max',
                                        'name': 'threshold-max'})
        }

    def __init__(self, *args, **kwargs):
        super(SensorCreateForm, self).__init__(*args, **kwargs)

class SensorUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Sensor
        fields = ('name', 'sensor_type', 'threshold_min', 'threshold_max')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Name',
                                        'name': 'sensor-name-edit'}),
            'sensor_type': forms.Select(attrs={'class': 'form-control',
                                        'placeholder': 'Type',
                                        'name': 'sensor-type-edit'}),
            'threshold_min': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Min',
                                        'name': 'threshold-min-edit'}),
            'threshold_max': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Max',
                                        'name': 'threshold-max-edit'})
        }

origen/sensor/views.py
from django.views.generic import CreateView 
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView 
from django.views.generic.edit import DeleteView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.urls import reverse
from . models import Sensor, Record
from . import forms
from django.shortcuts import get_object_or_404
from organization.models import Organization
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import datetime
from django.http import Http404
from django.utils import timezone

#Create your views here.
class SensorAdminRequiredMixin(UserPassesTestMixin, LoginRequiredMixin):
    def test_func(self):
        full_path = self.request.get_full_path()
        split_full_path = full_path.split("/")
        org_slug = split_full_path[3]
        org = Organization.objects.get(slug=org_slug)
        return self.request.user == org.admin
    
class CreateSensor(SensorAdminRequiredMixin, CreateView):
    model = Sensor
    form_class = forms.SensorCreateForm
    template_name = 'sensor/sensor_create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.organization = self.request.user.person.organization
        self.object.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('sensor:single', kwargs={'slug': self.object.organization.slug, 'pk': self.object.pk})
        
class SensorDetail(LoginRequiredMixin, DetailView):
    model = Sensor
    template_name = 'sensor/sensor_detail.html'

class UpdateSensor(SensorAdminRequiredMixin, UpdateView):
    model = Sensor
    form_class = forms.SensorUpdateForm
    template_name = 'sensor/sensor_update.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.organization = self.request.user.person.organization
        self.object.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('sensor:single', kwargs={'slug': self.object.organization.slug, 'pk': self.object.pk})

class SensorList(LoginRequiredMixin, ListView):
    model = Sensor
    template_name = 'sensor/sensor_list.html'

class DeleteSensor(SensorAdminRequiredMixin, DeleteView):
    model = Sensor
    template_name = 'sensor/sensor_delete.html'
     
    def get_success_url(self):
        return reverse_lazy('sensor:all', kwargs={'slug': self.object.organization.slug})


from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions

class SensorDetailAPI(APIView):
    # authentication_classes = (authentication.SessionAuthentication,)
    # permission_classes = (permissions.IsAuthenticated,)

    def get_object(self, pk):
        return (get_object_or_404(Sensor, pk=pk))


    def get(self, request, *args, **kwargs):
        sensor = self.get_object(self.kwargs.get('pk'))

        data = {
            "name": sensor.name,
            "organization": sensor.organization.name,
            "type": sensor.sensor_type,
            "value": sensor.value,
            "min": sensor.threshold_min,
            "max": sensor.threshold_max,
            "last_updated": sensor.last_updated,
        }
        return Response(data)

    
    def put(self, request, *args, **kwargs):
        sensor = self.get_object(self.kwargs.get('pk'))


        value = request.data['value']
        sensor.value = value
        sensor.save()

        data = {
            "name": sensor.name,
            "value": sensor.value,
            "updated": "True"
        }

        return Response(data)

class NewRecordAPI(APIView):
    def get_object(self, pk):
        return (get_object_or_404(Sensor, pk=pk))

    def put(self, request, *args, **kwargs):
        sensor = self.get_object(self.kwargs.get('pk'))

        value = request.data['value']
        created_at = request.data['created_at']       
        

        success = False
        
        try:
            Record.objects.create(
                sensor = sensor,
                created_at = created_at,
                value = value,
            )
            success=True
        except:
            success=False
            return Response({"success": success})
        
        data = {
            "name": sensor.name,
            "created_at": created_at,
            "value": value,
            "success": success,
        }
        
        return Response(data)


class RecordTimeAPI(APIView):

    def get_object(self, pk):
        return (get_object_or_404(Sensor, pk=pk))

    def get(self, request, *args, **kwargs):
        sensor = self.get_object(self.kwargs.get('pk'))
        offset = int(self.kwargs.get('offset'))
        time = self.kwargs.get('time')

        if (time=="days"):
            start_time = datetime.datetime.utcnow() - datetime.timedelta(days=offset)
            end_time = start_time + datetime.timedelta(days=1)
        elif(time=="hours"):
            start_time = datetime.datetime.utcnow() - datetime.timedelta(hours=offset)
            end_time = start_time + datetime.timedelta(hours=1)
        else:
            raise Http404

        records = Record.objects.filter(sensor__id=sensor.id, created_at__range=(start_time, end_time))

        data = {
            
        }
        for record in records:
            data[record.pk] = {
                "created_at": record.created_at,
                "value": record.value,
            }
            
        return Response(data)

class SensorListAPI(APIView):
    def get_object(self, slug):
        organization = get_object_or_404(Organization, slug=slug)
        return Sensor.objects.filter(organization=organization)

    def get(self, request, *args, **kwargs):
        sensors = self.get_object(self.kwargs.get('slug'))
        data = {}

        for sensor in sensors:
            is_active = False
            start_time = timezone.now() - datetime.timedelta(minutes=1)
            end_time = start_time + datetime.timedelta(minutes=1)
            
            if (start_time <= sensor.last_updated <= end_time):
                is_active = True
            else:
                is_active = False

            data[sensor.pk] = {
                "name": sensor.name,
                "organization": sensor.organization.name,
                "type": sensor.sensor_type,
                "value": sensor.value,
                "active": is_active,
            }
                 
        return Response(data)

origen/sensor/templates/sensor/sensor_create.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/orgcreate-gsdk-bootstrap-wizard.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style_sensorcreate.css' %}">
{% endblock %}

{% block content %}

<div>
    <!--   Big container   -->
    <div class="container">
        <div class="row secondcontainer">
            <div class="col-sm-8 col-sm-offset-1">

                <!--      Wizard container        -->
                <div class="wizard-container">

                    <!-- data-color controls the color of the active tab of the ACCOUNT/ABOUT/SIZE/LOCATION Nav Bar -->
                    <div class="card wizard-card hugecontainer" data-color="green" id="wizardProfile">
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            <!-- Title of Create Organization Page -->
                            <div class="wizard-header">
                                <h3>
                                    <b>BUILD</b> YOUR SENSOR <br>
                                    <small>&nbsp;</small>
                                </h3>
                            </div>
                            <!-- End of Title of Create Organization Page -->

                            <!-- Create Organization Page Nav Bar / Link to different sections -->
                            <div class="wizard-navigation">
                                <ul class="createorgnavbar">
                                    <li class="pickle2">
                                        <a class="createinside" href="#sensortype" data-toggle="tab">Type</a>
                                    </li>
                                    <li class="pickle2">
                                        <a class="createinside" href="#sensorname" data-toggle="tab">Name</a>
                                    </li>
                                    <li class="pickle2">
                                        <a class="createinside" href="#sensorsettings" data-toggle="tab">Settings</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- End of Create Organization Page Nav Bar / Link to different sections -->

                            <div class="tab-content">
                                <!-- Sensor Type Tab -->
                                <div class="tab-pane" id="sensortype">
                                    <div class="row commentcontainer">
                                        <div class="col-sm-6 col-sm-offset-1">
                                            <h4 class="info-text"> Select Sensor Type </h4>

                                            <div class="form-group">
                                                {{form.sensor_type}}
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <!-- End of Sensor Type Tab -->

                                <!-- Sensor Name Tab -->
                                <div class="tab-pane" id="sensorname">
                                    <div class="row commentcontainer">
                                        <div class="col-sm-6 col-sm-offset-1">
                                            <h4 class="info-text"> Label The Sensor </h4>
                                            <div class="form-group">
                                                {{form.name.errors}}
                                                {{form.name}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End of Sensor Name Tab -->

                                <!-- Sensor Setting Tab -->
                                <div class="tab-pane" id="sensorsettings">
                                    <div class="row commentcontainer">
                                        <div class="col-sm-6 col-sm-offset-1">
                                            <h4 class="info-text"> Warning Threshold </h4>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <!-- Minimum Threshold -->
                                            <h4 class="info-text"> Minimum </h4>
                                            <div class="threshold">
                                                {{form.threshold_min.errors}}
                                                {{form.threshold_min}}
                                            </div>
                                            <!-- End of Minimum Threshold -->
                                        </div>

                                        <div class="col">
                                            <!-- Maximum Threshold -->
                                            <h4 class="info-text"> Maximum </h4>
                                            <div class="threshold">
                                                {{form.threshold_max.errors}}
                                                {{form.threshold_max}}
                                            </div>
                                            <!-- End of Maximum Threshold -->
                                        </div>
                                        <!-- End of Sensor Setting Tab -->
                                    </div>
                                    <!-- End of Container -->
                                </div>
                            </div>

                            <!-- The next, create and previous button -->
                            <div class="wizard-footer height-wizard">
                                <div class="pull-right">
                                    <input type='button' class='btn btn-next btn-fill btn-wd btn-sm'
                                        name='next' value='Next' />
                                    <input type="submit" class='btn btn-finish btn-fill btn-wd btn-sm'
                                        value="Create" />
                                </div>
                                <div class="pull-left">
                                    <input type='button' class='btn btn-previous btn-fill btn-default btn-wd btn-sm'
                                        name='previous' value='Previous' />
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <!-- End of The next, create and previous button -->
                        </form>
                    </div>
                </div> <!-- wizard container -->
            </div>
        </div><!-- end row -->
    </div> <!--  big container -->

    {% endblock %}


    <!-- Scripts Block -->
    {% block scripts %}
    <!-- {{block.super}} -->
    <!--   Core JS Files   -->
    <script src="{% static 'js/orgcreate-jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/orgcreate-bootstrap.min.js' %}"></script>
    <script src="{% static 'js/orgcreate-jquery.bootstrap.wizard.js' %}"></script>

    <!--  Plugin for the Wizard -->
    <script src="{% static 'js/orgcreate-gsdk-bootstrap-wizard.js' %}"></script>

    <!-- More information about jquery.validate here: http://jqueryvalidation.org/	 -->
    <script src="{% static 'js/orgcreate-jquery.validate.min.js' %}"></script>

    <!-- javascript for the sensor create page -->
    <script type="text/javascript" src="{% static 'js/sensorcreate.js' %}"></script>

    {% endblock scripts %}

origen/sensor/templates/sensor/sensor_delete.html
{% extends "base.html" %}

{% block content %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock %}

<div class="container">
    <div class="row">
        <div class="col-lg-10 col-xl-9 mx-auto">
            <div class="card card-signin flex-row my-5">
                <!-- CONTENT -->
                <div class="card-body">
                    <form method='POST'>
                        {% csrf_token %}

                        <!-- CLOSE Button -->
                        <div class="text-right">
                            <a class="large" href="{% url 'sensor:all' slug=user.person.organization.slug %}"
                                style="color:rgb(27, 154, 75)"><i class="fas fa-times"></i></a>
                        </div>
                        <!-- /END CLOSE Button -->

                        <!-- BODY -->
                        <div class="text-center">
                            <h3 class="card-title text-center">Are you sure you want to delete "{{object.name}}"?</h3>
                            
                            <h1 class="card-title text-center" id="header2">
                                <!-- CANCEL Button -->
                                <a class="btn" href="{% url 'sensor:all' slug=user.person.organization.slug %}">Cancel</a>
                                <!-- /END CANCEL Button -->

                                &nbsp;

                                <!-- DELETE Button -->
                                <button type="submit" class="btn btn-danger" value="Delete">Delete</button>
                                <!-- /END DELETE Button -->
                            </h1>
                        </div>
                        <!-- /END BODY -->
                    </form>
                </div>
                <!-- /END CONTENT -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

origen/sensor/templates/sensor/sensor_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_sensordetail.css' %}">
{% endblock %}

{% block content %}

<div class="container-sensor-detail">
    <div class="row">
        <div class="col btn-sensor-detail">
            <div>
                <!-- LIST Button -->
                <a class="btn btn-success btn-sensor-detail-left"
                    href="{% url 'sensor:all' slug=user.person.organization.slug %}">List
                </a>
                <!-- /END LIST Button -->
                {% if user.person.organization.admin %}
                <!-- DELETE Button -->
                <a class="btn btn-danger btn-sensor-detail-right"
                    href="{% url 'sensor:delete' slug=user.person.organization.slug pk=sensor.pk %}">Delete
                </a>
                <!-- /END DELETE Button -->

                <!-- EDIT Button -->
                <a class="btn btn-success btn-sensor-detail-right"
                    href="{% url 'sensor:update' slug=user.person.organization.slug pk=sensor.pk %}">Edit
                </a>
                <!-- /END EDIT Button -->
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-12 sensor-detail-margin">
            <div class="card border-0 shadow">
                <div class="card-body2 text-center card-sensor1">
                    <div class="card3">
                        <div>
                            <h5 class="card-title mb-0 card-title-sensor">Min Threshold</h5>
                        </div>

                        <br>

                        <div class="card-text2 card-text-sensor">
                            <h5>{{sensor.threshold_min}}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 sensor-detail-margin">
            <div class="card border-0 shadow">
                <div class="card-body2 text-center card-sensor1">
                    <div class="card3">
                        <div>
                            <h5 class="card-title mb-0 card-title-sensor">Current Value</h5>
                        </div>
                        <br>
                        <div class="card-text2 card-text-sensor">
                            <h5 id="sensor-value">{{sensor.value}}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 sensor-detail-margin">
            <div class="card border-0 shadow">
                <div class="card-body2 text-center card-sensor1">
                    <div class="card3">
                        <div>
                            <h5 class="card-title mb-0 card-title-sensor">Max Threshold</h5>
                        </div>

                        <br>

                        <div class="card-text2 card-text-sensor">
                            <h5>{{sensor.threshold_max}}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 sensor-detail-margin">
            <canvas id="myChart" height="75"></canvas>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-sm-12 sensor-detail-margin">
            <div class="card border-0 shadow">
                <div style="padding: 10px; margin-bottom: 18px; margin-top: 20px;">
                    <canvas id="doughnut-chart"></canvas>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12 sensor-detail-margin">
            <div class="card border-0 shadow">
                <div style="padding: 10px; text-align: right;">
                    <canvas id="mixed-chart"></canvas>
                    <button id="update" class="btn btn-success" style="margin-right: 10px;">Update</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

<!-- Scripts Block -->
{% block scripts %}
{{block.super}}
<script src="{% static 'js/sensordetail.js' %}"></script>
{% endblock scripts %}

origen/sensor/templates/sensor/sensor_list.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_sensorlist.css' %}">
{% endblock %}

{% block content %}

<div class="container-sensor-list table-responsive-md">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Value</th>
                <th scope="col">Min</th>
                <th scope="col">Max</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for sensor in user.person.organization.sensors.all %}
            <tr id={{sensor.pk}}>
                <th scope="row">{{sensor.pk}}</th>
                <td><a href="{% url 'sensor:single' slug=user.person.organization.slug pk=sensor.pk %}"
                        style="display:block;">{{sensor.name|capfirst}}</a></td>
                <td>{{sensor.sensor_type|capfirst}}</td>
                <td>{{sensor.value}}</td>
                <td>{{sensor.threshold_min}}</td>
                <td>{{sensor.threshold_max}}</td>
                <td>
                    {% if user.person.organization.admin %}
                    <a class= "btn btn-success"
                        href="{% url 'sensor:update' slug=user.person.organization.slug pk=sensor.pk %}">Edit</a>&nbsp;&nbsp;
                    <a class="btn btn-danger"
                        href="{% url 'sensor:delete' slug=user.person.organization.slug pk=sensor.pk %}">Delete</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if user.person.organization.admin %}
    <!-- CREATE Button -->
    <a id="sensor-fab" class="fab" href="{% url 'sensor:create' slug=user.person.organization.slug %}">+</a>
    <!-- /END CREATE Button -->
    {% endif %}
</div>

{% endblock %}