origen/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from .forms import MyPasswordResetForm, MySetPasswordForm, MyPasswordChangeForm

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
<<<<<<< HEAD
<<<<<<< HEAD
]
=======
=======
>>>>>>> a3dffcd47fbe62378184722f860fb0c0938f8ec2
    path('login/', views.Login.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(from_email='forgot-password@origenair.com', form_class=MyPasswordResetForm), name='password_reset'), 
    # TODO: Above email account needs to be created, and email details must be included in Settings.py
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(form_class=MyPasswordChangeForm), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('profile/<username>', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.UserProfileUpdate.as_view(), name='profile_update'), 
]
<<<<<<< HEAD
>>>>>>> development
=======
>>>>>>> a3dffcd47fbe62378184722f860fb0c0938f8ec2

origen/organization/urls.py
from django.urls import path, include 
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'organization'

urlpatterns = [
    path('', views.OrgList.as_view(), name='all'),
    path('create/', views.CreateOrg.as_view(), name='create'),
    path('<slug>/', views.OrgProfile.as_view(), name='single'),
    path('<slug>/members/', views.OrgMembers.as_view(), name='members'),
    path('<slug>/update/', views.OrgProfileUpdate.as_view(), name='update'),
    path('<slug>/delete/', views.DeleteOrg.as_view(), name='delete'),     
    path('<slug>/join/', views.JoinOrg.as_view(), name='join'),
    path('<slug>/leave/', views.LeaveOrg.as_view(), name='leave'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

origen/origen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('sensor/', include('sensor.urls', namespace='sensor'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

origen/organization/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.urls import reverse
from colorful.fields import RGBColorField
from phonenumber_field.modelfields import PhoneNumberField


# circular import error or suggestion for when using Person
# from accounts.models import Person
from django.contrib.auth.models import User

# DEFAULT = '../origen/static/img/placeholder.jpg/'

def org_directory_path(instance, filename):
    return 'organization/logos/{0}'.format(filename)
    
class Organization(models.Model):
    
    name = models.CharField(max_length=25, null=False, blank=False)
    email = models.CharField(max_length=100, null=True, blank=True, default='None')
    street_name = models.CharField(max_length=100, null= True, blank=True)
    street_number = models.CharField(max_length=100, null= True, blank=True)
    city = models.CharField(max_length=100, null= True, blank=True)
    country = models.CharField(max_length=100, null= True, blank=True)
    website = models.CharField(max_length=200, null=True, blank=True)
    phone = PhoneNumberField(default='+12125552368', max_length=128, region=None, null=True, blank=True)
    description = models.TextField(max_length=255, default='', null=True, blank=True)
    color = RGBColorField(default='#000000')
    slug = models.SlugField(allow_unicode=True, unique=True)
    created_at = models.DateTimeField(default=timezone.now, null=False)
    
    admin = models.ForeignKey(User, related_name='organization_admin', null=True, blank=True, on_delete=models.SET_NULL)

    logo = models.ImageField(upload_to=org_directory_path, default='org/default_org_logo.png', null=True, blank=True)
   
    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("organization:single", kwargs={"slug": self.slug})

    # @property
    # def get_org_avatar_url(self):
    #     if self.org_avatar and hasattr(self.org_avatar, 'url'):
    #         return self.org_avatar.url
    #     else:
    #         return "../origen/static/img/placeholder.jpg/"
    #         # self.org_avatar.url = DEFAULT
    #         # return self.org_avatar.url

origen/organization/forms.py
from django import forms
from organization.models import Organization
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.forms.widgets import ClearableFileInput

class MyClearableFileInput(ClearableFileInput):
    initial_text = ''
    input_text = ''
    clear_checkbox_label = ''
    template_name = 'custom_clearable_file_input.html'


class OrganizationCreateForm(forms.ModelForm):

    class Meta:
        model = Organization
        fields = ('name', 'email', 'phone', 'website', 'street_name', 'street_number', 'city', 'country', 'description', 'color', 'logo')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputName',
                                        'placeholder': 'Organization',
                                        'name': 'Org-name'}),
            'email': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputEmail',
                                        'placeholder': 'Contact Email',
                                        'name': 'Org-email',}),
            'phone': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputPhone',
                                        'placeholder': 'Phone Number',
                                        'name': 'Org-phone',
                                        'required': False}),
            'website': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputWebsite',
                                        'placeholder': 'Website',
                                        'name': 'Org-Website'}),            
            'street_name': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputStreetName',
                                        'placeholder': 'Street Name',
                                        'name': 'street-name'}),
            'street_number': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputStreetNumber',
                                        'placeholder': 'Street Number',
                                        'name': 'street-number'}),
            'city': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputCity',
                                        'placeholder': 'City',
                                        'name': 'city'}),
            'country': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputCountry',
                                        'placeholder': 'Country',
                                        'name': 'country'}),
            'description': forms.Textarea(attrs={'class': 'form-control abouttextbox',
                                            'rows': '5',
                                            'id': 'inputDescription',
                                            'input type': 'text',
                                            'placeholder': 'Description',
                                            'name': 'description'}),
            'color': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputColor',
                                        'placeholder': 'Color',
                                        'name': 'color'}),
            'logo': MyClearableFileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(OrganizationCreateForm, self).__init__(*args, **kwargs)
    
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Organization.objects.filter(name=name).exists():
            raise ValidationError("Organization name is already in use")
        return self.cleaned_data.get('name')
    
class OrganizationUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Organization
        fields = ('email', 'phone', 'website', 'street_name', 'street_number', 'city', 'country', 'description', 'color', 'logo')
        
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Contact Email',
                                        'name': 'Org-email-edit',
                                        'required': False}),
            'phone': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Phone Number',
                                        'name': 'phone-number-edit',
                                        'required': False}),
            'website': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Website',
                                        'name': 'Org-Website-edit'}),
            'street_name': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputStreetName',
                                        'placeholder': 'Street Name',
                                        'name': 'street-name-edit'}),
            'street_number': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputStreetNumber',
                                        'placeholder': 'Street Number',
                                        'name': 'street-number-edit'}),
            'city': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputCity',
                                        'placeholder': 'City',
                                        'name': 'city-edit'}),
            'country': forms.TextInput(attrs={'class': 'form-control',
                                        'id': 'inputCountry',
                                        'placeholder': 'Country',
                                        'name': 'country-edit'}),
            'description': forms.Textarea(attrs={'class': 'form-control abouttextbox',
                                            'rows': '5',
                                            'id': 'description-edit',
                                            'input type': 'text',
                                            'placeholder': 'Description',
                                            'name': 'description-edit'}),
            'color': forms.TextInput(attrs={'class': 'form-control', 
                                        'id': 'color-edit',
                                        'placeholder': 'Color',
                                        'name': 'color-edit'}),
            'logo': MyClearableFileInput(),
        }

origen/organization/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView 
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView 
from django.views.generic.edit import DeleteView
from . forms import OrganizationUpdateForm
from . import forms
from . models import Organization
from accounts.models import Person
from django.http import Http404 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.urls import reverse
from django.shortcuts import get_object_or_404

class OrgAdminRequiredMixin(UserPassesTestMixin, LoginRequiredMixin):
    def test_func(self):
        self.object = self.get_object()
        return self.request.user == self.object.admin

# Create your views here.
class CreateOrg(LoginRequiredMixin, CreateView): 
    form_class = forms.OrganizationCreateForm
    template_name = 'organization/organization_create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.admin = self.request.user
        self.object.save()
        return super().form_valid(form)
     
class OrgProfile(DetailView):
    model = Organization
    template_name = 'organization/organization_profile.html'

class OrgMembers(DetailView):
    model = Organization
    template_name = 'organization/organization_members.html'

class OrgProfileUpdate(OrgAdminRequiredMixin, UpdateView):
    model = Organization
    form_class = OrganizationUpdateForm
    template_name = 'organization/organization_update.html'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('organization:single', kwargs={'slug': self.kwargs.get('slug')})

class OrgList(ListView): 
    model = Organization
    template_name = 'organization/organization_list.html'

class JoinOrg(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('organization:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        organization = get_object_or_404(Organization, slug=self.kwargs.get('slug'))
        if (self.request.user.person.organization):
            print("You're already in an organization!")
        else:
            self.request.user.person.organization = organization
            self.request.user.person.save()
        return super().get(request, *args, **kwargs)

class LeaveOrg(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('organization:single', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        organization = get_object_or_404(Organization, slug=self.kwargs.get('slug'))

        if (self.request.user.person.organization == organization):
            self.request.user.person.organization = None
            self.request.user.person.save()
        else:
            print("You're not a member of this organization!")
        return super().get(request, *args, **kwargs)

class DeleteOrg(OrgAdminRequiredMixin, DeleteView):
    model = Organization
    template_name = 'organization/organization_delete.html'
     
    def get_success_url(self):
        return reverse_lazy('organization:all')

origen/organization/templates/organization/organization_delete.html
{% extends "base.html" %}

{% block content %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock %}

<div class="container">
    <div class="row">
        <div class="col-lg-10 col-xl-9 mx-auto">
            <div class="card card-signin flex-row my-5">
                <!-- CONTENT -->
                <div class="card-body">
                    <form method='POST'>
                        {% csrf_token %}

                        <!-- CLOSE Button -->
                        <div class="text-right">
                            <a class="large" href="{% url 'organization:all' %}"
                                style="color:rgb(27, 154, 75)"><i class="fas fa-times"></i></a>
                        </div>
                        <!-- /END CLOSE Button -->

                        <!-- BODY -->
                        <div class="text-center">
                            <h3 class="card-title text-center">Are you sure you want to delete "{{object.name}}" organization?</h3>
                            
                            <h1 class="card-title text-center" id="header2">
                                <!-- CANCEL Button -->
                                <a class="btn" href="{% url 'organization:all' %}">Cancel</a>
                                <!-- /END CANCEL Button -->

                                &nbsp;

                                <!-- DELETE Button -->
                                <button type="submit" class="btn btn-danger" value="Delete">Delete</button>
                                <!-- /END DELETE Button -->
                            </h1>
                        </div>
                        <!-- /END BODY -->
                    </form>
                </div>
                <!-- /END CONTENT -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

origen/organization/templates/organization/organization_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div id="organization-list">
    <!-- LIST Organization -->
    <div class="row text-center">
        {% for organization in object_list %}
        <div class="col-md-4 list-card">
            <div class="card card-profile">
                <!-- PHOTO List -->
                <div class="card-header card-header-image">
                    {% if organization.logo %}
                    <img src="{{organization.logo.url}}" class="img">
                    <div class="colored-shadow" style="background-image: {{organization.logo.url}}; opacity: 1;"></div>
                    {% else %}
                    <img src="{% static 'img/contemplating.png' %}" class="img">
                    <div class="colored-shadow" style="background-image: {% static 'img/contemplating.png' %}; opacity: 1;"></div>
                    {% endif %}
                </div>
                <!-- /END PHOTO List -->

                <!-- BODY List -->
                <div class="card-body">
                    <h4 class="card-title">{{organization.name}}</h4>
                    <p class="card-text list-card-text">{{organization.description}}</p>
                </div>
                <!-- /END BODY List -->

                <!-- FOOTER List -->
                <div class="card-footer1 justify-content-center">
                    <a href="{% url 'organization:single' slug=organization.slug %}" class="btn btn-success">More Details</a>
                </div>
                <!-- /END FOOTER List -->
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- /END LIST Organization -->

    <!-- CREATE Button -->
    <a id="organization-fab" class="fab" href="{% url 'organization:create' %}">+</a>
    <!-- /END CREATE Button -->
</div>

{% endblock %}

<!-- Scripts Block -->
{% block scripts %}
{{block.super}}
{% endblock scripts %}

origen/organization/templates/organization/organization_members.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<!-- BANNER -->
<header class="bg-primary text-center py-5 mb-4 members-banner" style="background-color: {{organization.color}} !important;">
    <div class="container">
        <!-- NAME Organization -->
        <h1 class="font-weight-light text-white">{{organization.name}}</h1>
        <!-- Heading -->
        <h1 class="font-weight-light text-white">Meet the Team</h1>
    </div>
</header>
<!-- /END BANNER -->

<!-- CONTAINER -->
<div class="container member-container">
    <!-- LIST Member -->
    <div class="row">
        {% for person in organization.persons.all %}
        <a href="{% url 'accounts:profile' username=person.user.username %}" class="col-xl-3 col-md-6 mb-4 member-card">
            <div class="card border-0 shadow members-card">
                <!-- PHOTO Member -->
                <div class="card-avatar">
                    <img class="img" src="{{person.avatar.url}}">
                </div>
                <!-- /END PHOTO Member -->

                <!-- BODY Member -->
                <div class="card-body2 text-center">
                    <!-- NAME Member -->
                    <div><h5 class="card-title mb-0">{{person.user.get_full_name}}</h5></div>

                    <!-- JOB TITLE Member -->
                    <div class="text-black-50">{{person.job_title}}</div>

                    <!-- BIO Member -->
                    <div class="card-text2 text-black-50">{{person.biography}}</div>
                </div>
                <!-- /END BODY Member -->
            </div>
        </a>
        {% endfor %}
    </div>
    <!-- /END LIST Member -->
</div>
<!-- /END CONTAINER -->

{% endblock %}

<!-- Scripts Block -->
{% block scripts %}
{{block.super}}
{% endblock scripts %}

origen/organization/templates/organization/organization_profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<body class="profile-page">
    <!-- BACKGROUND Image -->
    <div class="page-header header-filter"
        style="background-image:url('https://i.pinimg.com/originals/e7/37/97/e73797e90db90a056e96291ca4f2a788.jpg');">
    </div>
    <!-- /END BACKGROUND Image -->

    <!-- MAIN Content -->
    <div class="main main-raised">
        <div class="profile-content">
            <div class="container">
                <div class="row">
                    <!-- HEADER -->
                    <div class="col-md-6 ml-auto mr-auto"> 
                        <!-- IMAGE Profile -->
                        <div class="card-avatar1">
                            {% if organization.logo %}
                            <img class="img" src="{{organization.logo.url}}">
                            {% else %}
                            <img class="img" src="{% static 'img/contemplating.png' %}">
                            {% endif %}
                        </div>
                        <!-- /END IMAGE Profile -->

                        <!-- NAME Profile -->
                        <div class="name text-center">
                            <h1>{{organization.name}}</h1>
                        </div>
                        <!-- /END NAME Profile -->

                        <!-- JOIN/LEAVE BUTTON -->
                        <div class="btn-join-leave text-center">
                            {% if not user.person.organization %}
                            <a href="{% url 'organization:join' slug=organization.slug %}"
                                class="btn btn-success btn-lg">Join</a>
                            {% endif %}
                            {% if user.person.organization == organization %}
                            <a href=" {% url 'organization:leave' slug=organization.slug %}"
                                class="btn btn-danger btn-lg">Leave</a>
                            {% endif %}
                        </div>                  
                        <!-- /END JOIN/LEAVE BUTTON -->
                    </div>
                    <!-- /END HEADER -->

                    <!-- LEFT COLUMN -->
                    <div class="col-md-8 mb-5 profile-left-content">
                        <!-- HEADER -->
                        <h2>What We Do</h2>
                        <hr>
                        <!-- /END HEADER -->

                        <!-- DESCRIPTION -->
                        <p>{{organization.description}}</p>
                        <!-- /END DESCRIPTION -->
                    </div>
                    <!-- /END LEFT COLUMN -->

                    <!-- RIGHT COLUMN -->
                    <div class="col-md-4 mb-5 profile-right-content">
                        <!-- HEADER -->
                        <h2>Contact Us</h2>
                        <hr>
                        <!-- /END HEADER -->

                        <!-- NAME/LOCATION -->
                        <address>
                            <strong>{{organization.name}}</strong>
                            <br>
                            {{organization.street_number}}
                            {{organization.street_name}}
                            </br>
                            {{organization.city}},
                            {{organization.country}}
                        </address>
                        <!-- /END NAME/LOCATION -->

                        <!-- PHONE/EMAIL -->
                        <address>
                            <abbr title="Phone">P:</abbr>
                            {{organization.phone}}
                            <br>
                            <abbr title="Email">E:</abbr>
                            <a href="mailto:#">{{organization.email}}</a>
                            <br>
                            <abbr title="Website">W:</abbr>
                            {{organization.website}}
                        </address>
                        <!-- /END PHONE/EMAIL -->

                        <!-- EDIT BUTTON -->
                        <address>
                            {% if user.person.organization == organization %}
                            <a class="btn btn-success" href="{% url 'organization:members' slug=user.person.organization.slug %}">Members</a>
                            {% endif %}
                            <!-- {% if user.person == organization.admin %} -->
                            {% if organization.admin %}
                            <a class="btn btn-success"
                                href="{% url 'organization:update' slug=organization.slug %}">Edit</a>
                            <a class="btn btn-danger btn-organization-right"
                                href="{% url 'organization:delete' slug=organization.slug %}">Delete
                            </a>
                            {% endif %}
                        </address>
                        <!-- /END EDIT BUTTON -->
                    </div>
                    <!-- /END RIGHT COLUMN -->

                    <!-- /END MAIN CONTENT -->
                </div>
            </div>
        </div>
    </div>
    <!-- /END MAIN Content -->
</body>

{% endblock %}

<!-- Scripts Block -->
{% block scripts %}
{{block.super}}
<!-- Create Profile Javascript -->
<script src="{% static 'js/createprofile.js' %}"></script>
{% endblock scripts %}