origen/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from .forms import MyPasswordResetForm, MySetPasswordForm, MyPasswordChangeForm

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
<<<<<<< HEAD
<<<<<<< HEAD
]
=======
=======
>>>>>>> a3dffcd47fbe62378184722f860fb0c0938f8ec2
    path('login/', views.Login.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(from_email='forgot-password@origenair.com', form_class=MyPasswordResetForm), name='password_reset'), 
    # TODO: Above email account needs to be created, and email details must be included in Settings.py
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(form_class=MyPasswordChangeForm), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('profile/<username>', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.UserProfileUpdate.as_view(), name='profile_update'), 
]
<<<<<<< HEAD
>>>>>>> development
=======
>>>>>>> a3dffcd47fbe62378184722f860fb0c0938f8ec2

origen/origen/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('sensor/', include('sensor.urls', namespace='sensor'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

origen/accounts/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User 
from organization.models import Organization
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

def user_directory_path(instance, filename):
    return 'person/avatars/{0}/{1}'.format(instance.user.username, filename)

class Person(models.Model):

    import pytz

    TIMEZONES = tuple(zip(pytz.common_timezones, pytz.common_timezones))

    user = models.OneToOneField(auth.models.User, on_delete=models.CASCADE, primary_key=True)
    
    alerts = models.BooleanField(default=True)
    avatar = models.ImageField(upload_to=user_directory_path, default='person/avatars/default.png', null=True, blank=True)
    biography = models.TextField(max_length=180, default='', null=True, blank=True)
    job_title = models.CharField(max_length=20, null=True, blank=True)
    organization = models.ForeignKey(Organization, related_name='persons', null=True, blank=True, on_delete=models.SET_NULL)
    phone_number = PhoneNumberField(default='+12125552368', max_length=128, region=None)
    time_zone = models.CharField(max_length=100, choices = TIMEZONES, default='America/Vancouver')
    
    def __unicode__(self):
        return self.user

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

origen/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django import forms
from accounts.models import Person
from django.forms import ModelForm
import pytz
from django.forms.widgets import ClearableFileInput
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'inputUsername', 'placeholder': 'Username', 'autocomplete': 'off'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'inputPassword','placeholder':'Password'}))

class PersonCreateForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'inputFirstName', 'placeholder': 'First Name', 'autocomplete': 'off'}),label='')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'inputLastName', 'placeholder': 'Last Name', 'autocomplete': 'off'}),label='')
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'inputUsername', 'placeholder': 'Username', 'autocomplete': 'off'}),label='')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'inputPassword', 'placeholder':'Password'}),label='')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'inputConfirmPassword', 'placeholder':'Confirm Password'}),label='')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'id': 'inputEmail', 'placeholder':'Email', 'autocomplete': 'off'}),label='')

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super(PersonCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email is already in use")
        return self.cleaned_data.get('email')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("Username is already in use")
        return self.cleaned_data.get('username')

    def save(self):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('email')
        user.save()
        person = Person.objects.create(user=user)
        person.save()
        return user

from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, PasswordChangeForm
class MyPasswordResetForm(PasswordResetForm):
    # email = forms.EmailField(label=_("Email"), max_length=254)
    # captcha = ReCaptchaField(widget=ReCaptchaV3)
    def __init__(self, *args, **kwargs):
        super(MyPasswordResetForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['id'] = 'inputEmail'
            visible.field.widget.attrs['placeholder'] = 'Email Address'
            visible.field.widget.attrs['autocomplete'] = 'off'

class MySetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(MySetPasswordForm, self).__init__(*args, **kwargs)
        for i, visible in enumerate(self.visible_fields()):
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'New Password'
            visible.field.widget.attrs['autocomplete'] = 'off'
            visible.field.widget.attrs['id'] = 'inputNewPassword'
            if (i==1):
                visible.field.widget.attrs['placeholder'] = 'Confirm New Password'
                visible.field.widget.attrs['id'] = 'inputConfirmPassword'

class MyPasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(MyPasswordChangeForm, self).__init__(*args, **kwargs)
        for i, visible in enumerate(self.visible_fields()):
            visible.field.widget.attrs['class'] = 'form-control change-password-input'
            visible.field.widget.attrs['placeholder'] = 'Old Password'
            visible.field.widget.attrs['autocomplete'] = 'off'
            visible.field.widget.attrs['id'] = 'inputOldPassword'
            if (i==1):
                visible.field.widget.attrs['placeholder'] = 'New Password'
                visible.field.widget.attrs['id'] = 'inputNewPassword'
            if (i==2):
                visible.field.widget.attrs['placeholder'] = 'Confirm New Password'
                visible.field.widget.attrs['id'] = 'inputConfirmPassword'

class MyClearableFileInput(ClearableFileInput):
    initial_text = ''
    input_text = ''
    clear_checkbox_label = ''
    template_name = 'custom_clearable_file_input.html'

class PersonUpdateForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('job_title', 'time_zone', 'phone_number', 'alerts', 'biography', 'avatar')

        widgets = {
            'job_title': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Job Title',
                                        'name': 'job-title-edit'}),
            'time_zone': forms.Select(choices=[(x, x) for x in pytz.common_timezones],
                                        attrs={'class': 'form-control',
                                        'placeholder': 'Time Zone',
                                        'name': 'time-zone-edit'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control',
                                        'placeholder': 'Phone Number',
                                        'name': 'phone-number-edit'}),
            'biography': forms.Textarea(attrs={'class': 'form-control',
                                            'rows': '5',
                                            'id': 'biography-edit',
                                            'input type': 'text',
                                            'placeholder': 'Biography',
                                            'name': 'biography-edit'}),
            'alerts': forms.CheckboxInput(attrs={'class': 'custom-control-input', 'id': 'subscribe_me', 'checked': ''}),
            'avatar': MyClearableFileInput()
        }

origen/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, get_user_model
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.http import Http404
from . forms import PersonUpdateForm
from . models import Person
from . import forms
User = get_user_model()

# Create your views here.
class SignUp(CreateView):
    form_class = forms.PersonCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

    def form_valid(self, form):     
        user = form.save()
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('home')

class Login(LoginView):
    form_class = forms.LoginForm
    template_name = 'accounts/login.html'

class UserProfile(ListView):
    model = Person
    template_name = 'accounts/profile.html' 

    def get_queryset(self):
        try:
            self.other_user = User.objects.get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['other_user'] = self.other_user
        return context

class UserProfileUpdate(UpdateView):
    model = Person
    form_class = PersonUpdateForm
    template_name = 'accounts/profile_update.html'

    def form_valid(self, form):
        print(form.instance.avatar)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:profile', kwargs={'username': self.object.user.username})

    def get_object(self):
        return self.request.user.person

origen/accounts/templates/accounts/login.html
{% extends "baseLogin.html" %}

{% block content %}
{% load static %}

<h3 class="card-title text-center">Welcome Back!</h3>

<form method="post">
    {% csrf_token %}
    {{form.non_field_errors}}

    <!-- USERNAME -->
    <div class="form-label-group">
        {{form.username}}
        <label for="inputUsername">Username</label>
    </div>
    <div class="form-label-group">
        {{form.username.errors}}
    </div>
    <!-- /END USERNAME -->

    <!-- PASSWORD -->
    <div class="form-label-group">
        {{form.password}}
        <label for="inputPassword">Password</label>
    </div>
    <div class="form-label-group">
        {{form.password.errors}}
    </div>
    <!-- /END PASSWORD -->

    <hr class="my-4">

    <!-- BUTTONS -->
    <button class="btn btn-lg btn-success btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">
        Log In</button>
    <div class="text-center">
        <a class="small" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
    </div>
    <div class="text-center">
        <a class="small" href="{% url 'accounts:signup' %}">Register</a>
    </div>
    <!-- /END BUTTONS -->
</form>
<!-- /END CONTENT -->

{% endblock %}

origen/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <!-- PROFILE PHOTO -->
            <div class="col-md-4">
                <div class="profile-img">
                    <!-- PROFILE IMAGE -->
                    <img src="{{other_user.person.avatar.url}}" alt=""/>
                    <!-- /END PROFILE IMAGE -->
                </div>
            </div>
            <!-- /END PROFILE PHOTO -->

            <!-- PROFILE HEAD -->
            <div class="col-md-6">
                <div class="profile-head">
                    <!-- FULL NAME -->
                    <h5>{{other_user.get_full_name}}</h5>
                    <!-- /END FULL NAME -->
                    
                    <br>
                    
                    <!-- TAB SELECTION -->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <!-- ABOUT -->
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                aria-controls="home" aria-selected="true">About</a>
                        </li>
                        <!-- /END ABOUT -->

                        <!-- TIMELINE -->
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                                aria-controls="profile" aria-selected="false">Details</a>
                        </li>
                        <!-- /END TIMELINE -->
                    </ul>
                    <!-- /END TAB SELECTION -->
                </div>
            </div>
            <!-- /END PROFILE HEAD -->

            {% if user == other_user %}
            <!-- EDIT PROFILE BUTTON -->
            <div class="col-md-2">
                <div class="text-center">
                    <a class="btn btn-success" href="{% url 'accounts:profile_update' %}">Edit Profile</a>
                </div>
            </div>
            <!-- /END EDIT PROFILE BUTTON -->
            {% endif %}
        </div>

        <div class="row">
            <div class="col-md-4">
                <!-- <div class="profile-work">
                    <p>WORK LINK</p>
                    <a href="">Website Link</a><br />
                    <a href="">Bootsnipp Profile</a><br />
                    <a href="">Bootply Profile</a>
                </div> -->
            </div>

            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <!-- ABOUT TAB -->
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        
                        <!-- JOB TITLE -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Job Title</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.person.job_title}}</p>
                            </div>
                        </div>
                        <!-- /END JOB TITLE -->

                        <!-- ORGANIZATION -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Organization</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.person.organization}}</p>
                            </div>
                        </div>
                        <!-- /END ORGANIZATION -->

                        <!-- TIME ZONE -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Time Zone</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.person.time_zone}}</p>
                            </div>
                        </div>
                        <!-- /END TIME ZONE -->

                        <!-- BIO -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Bio</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p style="overflow-wrap: break-word;">{{other_user.person.biography}}</p>
                            </div>
                        </div>
                        <!-- /END BIO -->
                    </div>
                    <!-- /END ABOUT TAB -->

                    <!-- TIMELINE TAB -->
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        
                        <!-- USERNAME -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Username</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.username}}</p>
                            </div>
                        </div>
                        <!-- /END USERNAME -->

                        <!-- FIRST NAME -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>First Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.first_name}}</p>
                            </div>
                        </div>
                        <!-- /END FIRST NAME -->

                        <!-- LAST NAME -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Last Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.last_name}}</p>
                            </div>
                        </div>
                        <!-- /END LAST NAME -->

                        <!-- EMAIL -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.email}}</p>
                            </div>
                        </div>
                        <!-- /END EMAIL -->

                        <!-- PHONE NUMBER -->
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{other_user.person.phone_number}}</p>
                            </div>
                        </div>
                        <!-- /END PHONE NUMBER -->
                    </div>
                    <!-- /END TIMELINE TAB -->
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

<!-- Scripts Block -->
{% block scripts %}
    {{block.super}}
{% endblock scripts %}

origen/accounts/templates/accounts/signup.html
{% extends "baseLogin.html" %}

{% block content %}
{% load static %}

<h5 class="card-title text-center">Register</h5>

<form method=post class="form-signin">
    {% csrf_token %}
    {{form.non_field_errors}}
    
    <!-- FIRST NAME -->
    <div class="form-label-group">
        {{form.first_name}}
        <label for="inputFirstName">First Name</label>
    </div>
    <div class="form-label-group">
        {{form.first_name.errors}}
    </div>
    <!-- /END FIRST NAME -->

    <!-- LAST NAME -->
    <div class="form-label-group">
        {{form.last_name}}
        <label for="inputLastName">Last Name</label>
    </div>
    <div class="form-label-group">
        {{form.last_name.errors}}
    </div>

    <hr>

    <!-- /END LAST NAME -->

    <!-- USERNAME -->
    <div class="form-label-group">
        {{form.username}}
        <label for="inputUsername">Username</label>
    </div>
    <div class="form-label-group">
        {{form.username.errors}}
    </div>
    <!-- /END USERNAME -->

    <!-- EMAIL ADDRESS -->
    <div class="form-label-group">
        {{form.email}}
        <label for="inputEmail">Email Address</label>
    </div>
    <div class="form-label-group">
        {{form.email.errors}}
    </div>
    <!-- /END EMAIL ADDRESS -->

    <hr>

    <!-- PASSWORD -->
    <div class="form-label-group">
        {{form.password1}}
        <label for="inputPassword">Password</label>
    </div>
    <div class="form-label-group">
        {{form.password1.errors}}
    </div>
    <!-- /END PASSWORD -->

    <!-- CONFIRM PASSWORD -->
    <div class="form-label-group">
        {{form.password2}}
        <label for="inputConfirmPassword">Confirm Password</label>
    </div>
    <div class="form-label-group">
        {{form.password2.errors}}
    </div>
    <!-- /END CONFIRM PASSWORD -->

    <hr class="my-4">

    <!-- BUTTONS -->
    <button class="btn btn-lg btn-success btn-block text-uppercase" type="submit">Register</button>
    <a class="d-block text-center mt-2 small" href="{% url 'accounts:login' %}">Log In</a>
    <!-- /END BUTTONS -->
</form>
<!-- /END CONTENT -->

{% endblock %}